lpath <- list.dirs("~/.checkpoint/2015-02-09/lib",
                   recursive=TRUE,full.names=TRUE)[3]

.libPaths(lpath)
library(tm)
library(topicmodels)
library(OAIHarvester)
library(RISmed)
library(Rmpfr)
library(XML)
library(class)
library(dendextend)
library(ellipse)
library(igraph)
library(languageR)
library(maxent)
library(plyr)
library(proxy)
library(randomForest)
library(rbenchmark)
library(skmeans)
library(wordcloud)
